### ISSUE TITLE
Why is drupal/coder locked to 8.3.9?

### ISSUE THREAD

**Issue by vever001** [ec-europa/oe-code-review#127]
Hello,

While upgrading a project, I noticed that release 1.5.0 of openeuropa/code-review locks drupal/coder to 8.3.9: 
https://github.com/openeuropa/code-review/blob/1.5.0/composer.json#L8
I was on openeuropa/code-review:1.5.0 and for some reason `composer update` causes  openeuropa/code-review to be downgraded back to 1.4.0.

Is there any good reason for this?
Couldn't we relax a bit the requirement to e.g: `"drupal/coder": "^8.3"` ?

Thank you,
Hervé

**Comment by brummbar** [comment]
It was probably locked due to some incompatibilities at that moment caused by new rules.
