### ISSUE TITLE
Reconsider having commit messages starting with hash (#)

### ISSUE THREAD

**Issue by claudiu-cristea** [ec-europa/oe-code-review#7]
Having commit messages starting with a hash can be very annoying and is not used in most of the projects. Drupal.org, in [Commit messages - providing history and credit](https://www.drupal.org/node/2877535), explicitly states against using hash (#) as the first character in commit message:

> Important: Do NOT begin your commit message with the # symbol. While this was a best practice with CVS, it will cause Git to remove the commit message entirely in certain situations (e.g. git rebase -i).

The reason is that, sometimes, the commit messages get edited in an editor (for example on interactive rebase). Is such cases all lines prefixed with hash (#) are considered comments and are removed from the commit message.

See also:
- https://stackoverflow.com/questions/2788092/start-a-git-commit-message-with-a-hashmark

**Comment by drupol** [comment]
Hi,

I'm also in favor of this, I experienced the same problem when rebasing.
Lines beggining with # are considered as comments and thus, discarded.

**Comment by ademarco** [comment]
Yep, totally on board with this guys! We will set on `Issue #123:` for now.
